inicialize Project
JavierAybar/BookStore_React_Redux pull request #1
Opened 2023-08-17 22:14 UTC by JavierAybar

# BookStore `React` 📚 
- Use React Router.
- Use React components.

## Project requirements

- [ ] Setup a new React application using [Create React App](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app)

- [ ] Create a directory for your reusable components: `/components`.
- [ ] Install [React Router V6](https://reactrouter.com/en/main/start/tutorial#setup)
- [ ] [Setup your router](https://reactrouter.com/en/main/start/tutorial#adding-a-router) inside of <App>
- [ ] Add 2 routes in your application.
- [ ] Create components inside of the `/components` directory:
- Contains individual book state, as well as a button to delete the book.
- Contains a list to renders individual books.
- Contains a form to create new books.
- Contains a navigation to link to the 2 routes you created.

2023-08-17 22:43 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @JavierAybar 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Use React Router.
- ✔️ Use React components.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 22:43 UTC, abdulhamiid commented on src/pages/Books.js
> +      </div>
According to the project requirements,

![image](https://github.com/JavierAybar/BookStore_React_Redux/assets/78251927/f4305e84-1ae4-430c-9c25-b1582dd7cfe4)

I suggest you create a `<BookList>` component that renders a list of books using the `<Book>` component. 🛠💪

2023-08-17 22:43 UTC, abdulhamiid commented on src/pages/Books.js
> +        <Book />
Kindly take the book data as a prop and renders the title and the author 👍

```JavaScript
<Book title="The Hunger Games" author="Suzanne Collins" />
```
`Props` is a special keyword in React, which stands for properties and is being used for passing data from one component to another similar to how the arguments are passed in a function. 🤗

2023-08-18 03:02 UTC, Efiamotu-1 approved these changes
Hi @JavierAybar , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 12:32 UTC, merged