Connect to API
JavierAybar/BookStore_React_Redux pull request #4
Opened 2023-08-24 21:10 UTC by JavierAybar

> # BookStore 📚 `ES6` `React` `Redux`

✅ _Make use of the [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) as your backend._
✅ _Use [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) to make your HTTP requests to the backend._
✅ _Fetch your books from the Bookstore API after the component has rendered._
✅ _Refactor your add book and remove book features to persist your changes in the server._
✅ _Your application should behave the same way after the refactoring._

2023-08-24 21:22 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @JavierAybar, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 21:22 UTC, anagudelogu commented on src/redux/books/booksSlice.js
> +    thunkAPI.dispatch(getListBooks());
- [ ] You did a good job working on this milestone! 💯 However, it would be great to handle this piece of logic inside your reducer instead of doing it directly into the thunk itself. You don't really need to fetch your books again after a book creation/deletion. Instead, you can do something like this inside the `extraReducers` object in your slice:

```js
  extraReducers: (builder) => {
    ...
    builder.addCase(deleteBook.fulfilled, (state, action) => {
      // Given the return value of this thunk is the book ID:
      state.books = state.books.filter((book) => book.id !== action.payload)
    });
    ....
  },
```

Applying this change will improve your app's performance, providing a better experience for the end user. Please consider applying it! 🤓 🔧

2023-08-24 21:22 UTC, anagudelogu commented on src/redux/books/booksSlice.js
> +    thunkAPI.dispatch(getListBooks());
- [ ] You can do exactly the same with this one:

```js
  extraReducers: (builder) => {
    ...
    builder.addCase(createNewBook.fulfilled, (state, action) => {
      // Given the return value of this thunk is the book:
      state.books.push(action.payload);
    });
    ....
  },
```

Please consider applying it! 🤓 🔧

2023-08-25 14:24 UTC, TadesseDev approved these changes
### Hi @JavierAybar 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![AmazingCreepyFrogmouth-max-1mb](https://user-images.githubusercontent.com/69077061/255314805-13569584-0c0e-4b38-a0bd-94d901ba8a1e.gif)




## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 14:32 UTC, merged